#!/usr/bin/env node

'use strict';

var knox = require('knox');

function isProduction() {
  return process.env.NODE_ENV === 'production';
}

function bucket() {
  if (isProduction()) {
    return 'gocardless.com';
  } else {
    return 'staging.gocardless.com';
  }
}

var client = knox.createClient({
  key: process.env.GC_AWS_ACCESS_KEY,
  secret: process.env.GC_AWS_ACCESS_KEY,
  bucket: bucket(),
  region: 'eu-west-1'
});

